fix all_host_ids reference
introduced in:
ManageIQ/manageiq#20149

```
  1) EmsClusterController#show render listnav partial correctly for timeline page
     Failure/Error: sdate, edate = @tl_record.first_and_last_event(@tl_options.evt_type)

     NameError:
       undefined local variable or method `all_host_ids' for #<EmsCluster:0x000055e3fd7fb930>
       Did you mean?  all_relationship_ids
```