find_or_initialize_by_name is removed in rails 5
Fixes an error during seeding:
```
NoMethodError: undefined method `find_or_initialize_by_name' for #<Class:0x007ffd96e35120>
/Users/joerafaniello/.gem/ruby/2.2.4/gems/activerecord-5.0.0.beta2/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
/Users/joerafaniello/Code/manageiq/app/models/scan_item.rb:57:in `preload_default_profile'
/Users/joerafaniello/Code/manageiq/app/models/scan_item.rb:52:in `seed'
```