Fix undefined method while getting database configuration
`ActiveRecord::Base.configurations` no longer responds to `[]`
like a hash.

```
lib/evm_database.rb:153:in `host': undefined method `[]' lib/evm_database.rb:153:in `host': undefined method `[]'
(ActiveRecord::Base.configurations[ENV['RAILS_ENV']] || {})['host']
                                  ^^^^^^^^^^^^^^^^^^
lib/evm_database.rb:157:in `local?'
lib/workers/evm_server.rb:236:in `configure_server_roles'
lib/workers/evm_server.rb:127:in `start_server'
```