`connection` is deprecated as an instance method, call it on the class.
Fixes: NameError undefined local variable or method `connection' for ActiveRecord model class

See: https://github.com/rails/rails/issues/15330
Removed here: https://github.com/rails/rails/commit/992d87db02507363a4ad4ab40a3e4c4b32cf0408