Service#direct_vms - compact to prevent API bug
When accessing /api/services/10000000000115?attributes=aggregate_all_vm_cpus, you can get  an API error - NoMethodError - "undefined method `cpu_total_cores' for nil:NilClass"

That happens because `direct_vms` can return `[nil]`, which means `all_vms` will also return `[nil]`.

So fixing direct_vms to prevent nils