Fix EmsEvent#manager_refresh full-refresh target
If an ems does not support targeted refresh then the ems object is
returned.  In this case the check for `#empty?` was causing failures:
```
NoMethodError (undefined method `empty?' for #<ManageIQ::Providers::Redhat::InfraManager:0x0000558842fee5c8>)
Did you mean?  emstype?
```