Update to v6 to work with a change in the github API
This should fix an issue we started seeing in the past several hours:
Error: Cannot read properties of undefined (reading 'number')

See: https://github.com/peter-evans/create-pull-request/issues/2790

[skip ci]