debug toasts - Fix an error when closing an error message
Closing an error popup triggers `TypeError: $ctrl._close is not a function at close`

Now passing the right function..

Introduced in #6623