ConfigurationHelper constant was duplicated leading to test failures.
app/helper/configuration_helper.rb was added in: 6e55c5a85ee
spec/support/configuration_helper.rb was added in: da64b0519ada
(duplicating the constant name)

The changes here fix an error seen when running this spec in isolation or randomly when part of the test suite:

```
1) ConfigurationHelper.render_view_buttons should render HTML tags for compare view button
     Failure/Error: helper.render_view_buttons(resource, view)
     NoMethodError:
       undefined method `render_view_buttons' for #<#<Class:0x007fd662880528>:0x007fd662803230>
     # ./spec/helpers/configuration_helper_spec.rb:9:in `block (4 levels) in <top (required)>'

  2) ConfigurationHelper.render_view_buttons should render HTML tags for compare view button
     Failure/Error: helper.render_view_buttons(resource, view)
     NoMethodError:
       undefined method `render_view_buttons' for #<#<Class:0x007fd662880528>:0x007fd66176b490>
     # ./spec/helpers/configuration_helper_spec.rb:9:in `block (4 levels) in <top (required)>'

  3) ConfigurationHelper.render_view_buttons should render HTML tags for tagging view button
     Failure/Error: helper.render_view_buttons(resource, view)
     NoMethodError:
       undefined method `render_view_buttons' for #<#<Class:0x007fd662880528>:0x007fd661722b78>
     # ./spec/helpers/configuration_helper_spec.rb:9:in `block (4 levels) in <top (required)>'
```