sneakernet_ca requires a newer certmonger not hosted publicly.
Nightly builds were failing with an unclear dependency error in the installer.

After doing an OS-only appliance build, yum install indicated the real error:

Error: Package: sneakernet_ca-0.1-2.el6.noarch (jrafanie-manageiq-scl)
           Requires: certmonger >= 0.75.8
           Installing: certmonger-0.61-3.el6.x86_64 (base)
               certmonger = 0.61-3.el6

Once this is available publicly, we can use sneakernet_ca.