ConnectionPool v3.0 introduces breaking changes
Dalli does not use kwargs for creating a connection pool object which
throws an ArgumentError exception:

```
ArgumentError: wrong number of arguments (given 1, expected 0) (ArgumentError)
~/.gem/ruby/3.3.0/gems/connection_pool-3.0.1/lib/connection_pool.rb:48:in `initialize'
~/.gem/ruby/3.3.0/gems/dalli-3.2.8/lib/rack/session/dalli.rb:142:in `new'
~/.gem/ruby/3.3.0/gems/dalli-3.2.8/lib/rack/session/dalli.rb:142:in `build_data_source'
~/.gem/ruby/3.3.0/gems/dalli-3.2.8/lib/rack/session/dalli.rb:70:in `initialize'
```