[rails6][EvmDatabase] Fix .host
Rails 6 changed database configuration to support multi-db environments:

https://github.com/rails/rails/pull/33637

So how one accesses the `@config` hash has changed.

The original error suggested the following:

    NotImplementedError: `ActiveRecord::Base.configurations` in Rails 6
    now returns an object instead of a hash. The `fetch_path` method is
    not supported. Please use `configs_for` or consult the documentation
    for supported methods.

However, there is no `[]` or `host` method, so it would require calling
`configs_for(env_name: ENV["RAILS_ENV"]).config['host']`.

This solution seemed like the more terse solution.