Dialog#dialog_fields - skip nils
This causes dialog_fields to not return nils when a dialog tab has no fields.

Previously, if `dialog_tabs[*].dialog_fields` returned nil, #content would fail with
`NoMethodError: undefined method 'values' for nil:NilClass`.