Do not pass nil to the assignment mixin
Addressing: [NoMethodError]: undefined method `base_model' for NilClass:Class  Method:[rescue in _async_generate_table]
app/models/mixins/assignment_mixin.rb:146:in `block in get_assigned_for_target'
app/models/mixins/assignment_mixin.rb:146:in `collect'
app/models/mixins/assignment_mixin.rb:146:in `get_assigned_for_target'
app/models/chargeback/rates_cache.rb:13:in `rates'
app/models/chargeback/rates_cache.rb:7:in `get'
app/models/chargeback.rb:9:in `block in build_results_for_report_chargeback'
app/models/chargeback/consumption_history.rb:31:in `block (2 levels) in for_report'

Introduced in 31fac86a962f16c080f453a44dcd20345b8fd24e

Lesson learned: when you see two lists with [].compact, it is usually
good idea to use compact too.

If we merged https://github.com/ManageIQ/manageiq/pull/14090 we wouldn't
see this at customer.