Fixes issues with accessing attributes of a workflow.
With a request like: GET /api/requests/4?attributes=workflow.values

One would get the following error.
{
  "error": {
    "kind": "internal_server_error",
    "message": "undefined method `has_attribute?' for ManageIQ::Providers::Vmware::InfraManager::ProvisionWorkflow:Class",
    "klass": "NoMethodError"
  }
}

The issue at hand was not really workflow related but a bug in the attr_accessible? method, which did not
always function properly.

Fixed the method and added rspec to test the above condition.