Use pool's with_connnection since establish_connection returns a pool
Note, we only get to this failing code in rake db:migrate if you have
replication enabled with a remote region that needs to be migrated.

From the output below, you can see the global is waiting on the remote:

```
== Migrating database ==
** Enabling rack session debug logger
** ManageIQ master, codename: Uhlmann
Waiting for remote region 1 to run migration 20260415170724.bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

undefined method `connection' for an instance of ActiveRecord::ConnectionAdapters::ConnectionPool

Caused by:
NoMethodError: undefined method `connection' for an instance of ActiveRecord::ConnectionAdapters::ConnectionPool (NoMethodError)

      c = SubscriptionHelper.establish_connection.connection.raw_connection
```