Delay converting these to ARel for now.
MiqRegion#active_miq_servers uses a finder_sql that can't be then chained with .includes because ActiveRecord loses it's mind trying to determine the foreign key reference.

has_many :active_miq_servers,     :finder_sql => lambda { |_| MiqServer.in_region(region_number).where(:status => ['started', 'starting']).to_sql }, :class_name => "MiqServer"

Results in this error:
  PGError: ERROR:  column miq_servers.miq_region_id does not exist
    LINE 1: SELECT "miq_servers".* FROM "miq_servers"  WHERE "miq_server...

We'll tackle this separately in the rails4 branch.