Find correct klass for rbac check for retirevms
One would think that retirevms method would operate on Vm records.
That's not the case. Caveat programmer!

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1442691

Introduced in 457b08584b043a981d23c28f23868fbd924f93b3.

Addressing:
Error caught: [NoMethodError] undefined method `all' for nil:NilClass
lib/rbac/filterer.rb:545:in `apply_scope'
lib/rbac/filterer.rb:205:in `search'
lib/rbac/filterer.rb:112:in `search'
lib/rbac.rb:3:in `search'
manageiq-ui-classic-d32ec1b1bfc2/app/controllers/application_controller.rb:2265:in `assert_rbac'
manageiq-ui-classic-d32ec1b1bfc2/app/controllers/mixins/checked_id_mixin.rb:35:in `find_checked_ids_with_rbac'
manageiq-ui-classic-d32ec1b1bfc2/app/controllers/application_controller/ci_processing.rb:219:in `retirevms'